name: jeepmiyabe
description: "A new Flutter project for jeepney routes in Angeles City."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.8

  cupertino_icons: ^1.0.8

  # --- Map and Routing Dependencies ---
  google_maps_flutter: ^2.9.0
  flutter_dotenv: ^5.1.0
  collection: ^1.18.0
  
  # FIX: Added geolocator to enable GPS functions in map_screen.dart
  geolocator: ^10.1.0 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # FIX: Moved linting rules to dev_dependencies (where they belong)
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    # FIX: Added explicit assets/data/ folder needed for loading routes_data.json
    - assets/data/
    - assets/
