name: jeepmiyabe
description: "A new Flutter project for jeepney routes in Angeles City."
publish_to: "none" # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Backend and Configuration
  supabase_flutter: ^2.0.8
  flutter_dotenv: ^5.1.0 # To securely load Supabase keys from .env

  # UI and Core packages
  cupertino_icons: ^1.0.8
  
  # --- Map and Routing Dependencies ---
  google_maps_flutter: ^2.9.0 # Main map view
  geolocator: ^10.1.0 # For getting user's current GPS location
  
  # Routing/Pathfinding Utilities
  collection: ^1.18.0 # For PriorityQueue implementation in route finding
  
  # UI Specific dependencies
  font_awesome_flutter: ^10.6.0 # ADDED: Required for the car icon used in map_screen.dart UI
  pin_code_fields: ^8.0.1 # Likely for phone number/OTP login flow

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules are correctly placed here.
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    # Ensure assets/data is properly configured to load JSON data for the network graph
    - assets/data/
    - assets/
